name: Nightly Docker Build

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '*/5 * * * *'
env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_TOKEN }}
  
jobs:
  build:

    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 48n6e/rtsp-to-html:nightly
